# Generated by Django 3.0.6 on 2020-05-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborate_Files_A00',
            fields=[
                ('date_timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('collaborate_files_a00_rec', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=250)),
                ('file_name', models.CharField(max_length=250)),
                ('notes', models.TextField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Contact')),
                ('module_used_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Module')),
            ],
        ),
    ]
