# Generated by Django 3.0.6 on 2020-05-21 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborate_Files_A00',
            fields=[
                ('date_timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('collaborate_files_a00_rec', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], max_length=20)),
                ('file_name', models.CharField(max_length=250)),
                ('notes', models.TextField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('module_used_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Module')),
            ],
        ),
    ]
