# Generated by Django 3.0.6 on 2020-05-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborate_files_a00',
            name='category',
            field=models.CharField(choices=[(1, 'Image'), (2, 'Audio'), (3, 'Video'), (4, 'Document')], max_length=250),
        ),
    ]
