# Generated by Django 3.0.6 on 2020-05-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20200517_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborate_files_a00',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Image'), (2, 'Audio'), (3, 'Video'), (4, 'Document')]),
        ),
    ]
